### ISSUE TITLE
Access RAM

### ISSUE THREAD

**Issue by Kev0123** [gihad/streamer#10]
Hi there,

first of all great idea! Is there any way to write the files to the host's RAM instead of normal FS mount?
I want to run this on my diskstation and the HDD Heads are goind crazy with this amount of short writings.
Regards Kev

**Comment by gihad** [comment]
That's a good idea. There are multiple way of achieving this, you could create a `ramdisk` and use it in docker but docker has a similar solution already built-in, check https://docs.docker.com/storage/tmpfs/
