### ISSUE TITLE
rotate stream

### ISSUE THREAD

**Issue by Hoodah** [gihad/streamer#12]
For some reason the google display started showing the video rotated 90 degrees. I'm not sure what the syntax is to get it to rotate back?

**Comment by gihad** [comment]
Hey, search for something along the lines of `ffmpeg rotate video`
Found this link: https://ostechnix.com/how-to-rotate-videos-using-ffmpeg-from-commandline/

You could add the parameters (to rotate) to the ffmpeg command here: https://github.com/gihad/streamer/blob/master/create_ffmpeg_cmd.sh#L35
