### ISSUE TITLE
Suggestions for reducing latency?

### ISSUE THREAD

**Issue by ChrisRomp** [gihad/streamer#15]
Fantastic work. I'm hoping to use this to stream UniFi protect cam streams to Chromecast devices. I've got it working in general but there's about a ~20-30 second latency in the stream, accessing it via VLC.  It seems to be the same regardless of the stream resolution selected.

I realize with ffmpeg in the mix, some latency is to be expected. Are there configuration options you would suggest to help reduce latency / optimize the stream?

Thank you!

**Comment by coen17st** [comment]
I wondered exactly the same. i am also experiencing 30sec delay. i tried to modify the FFMPEG cmd but no result so far.

**Comment by apedance** [comment]
I would be interested in less delay as well.
Thanks for your work.

**Comment by Shad0wWulf** [comment]
would also like to know :)

**Comment by ChrisRomp** [comment]
Seems like a wontfix...
