### ISSUE TITLE
Use UDP instead of TCP

### ISSUE THREAD

**Issue by ivanjx** [gihad/streamer#18]
hi, is it possible to use UDP instead of TCP from within docker container? sometimes my wifi and camera's connection are bad and using UDP would make the stream a bit smoother in my case. thanks.

**Comment by gihad** [comment]
I don't know how that would play out in practice as I haven't tried it, but in theory HLS is adaptive so it's probably better than UDP for dealing with "bad" connections.

**Comment by ivanjx** [comment]
for anyone thats curious, i played around with it and you can actually use udp instead of tcp if you want to. you need to use `min_port` and `max_port` parameter as described in the ffmpeg rtsp docs and just need to publish the ports. example if `min_port` is 10000 and `max_port` is 10010 then the docker publish parameter is `-p 10000-10010:10000-10010/udp`.
