### ISSUE TITLE
How to Play HLS stream on chromecast device?

### ISSUE THREAD

**Issue by harshiddhmania** [gihad/streamer#2]
Hi @gihad,

With the use of ffmpeg, i am able to convert and playback of HLS video (.m3u8 file) on Google Chrome Browser with HLS plugin. But not able to understand that how would i play the HLS video on chromecast device. 
So can you please provide some details on how to play HLS stream on Chromecast device. Thanks in advance.

Regards,
HM

**Comment by gihad** [comment]
Did you experience this while trying the code from this project or this just a general question?

**Comment by gihad** [comment]
@harshiddhmania When I was working on this project I found out that the Chromecast is very picky on the what kind of audio and video codec it supports, check this line in the shell script: https://github.com/gihad/streamer/blob/master/create_ffmpeg_cmd.sh#L13

At the time I found out that you need acc and h264 for the chromecast to accept the HLS stream and that's part of what this project does.
