### ISSUE TITLE
Default Audio Defined twice, etc.

### ISSUE THREAD

**Issue by sreknob** [gihad/streamer#3]
Hi-
Amazing work on this project!
Just reviewing the create_ffmpeg_cmd.sh and saw that DEFAULT_AUDIO is defined twice. I think that line 28 should be DEFAULT_VIDEO=h264 instead, no?
Also, I see that you defined IS_RTSP for using tcp input but I don't see it being used in your command line and you have always set to tcp input. I actually saw this because I am interested in using udp for some cheap unreliable webcams.... Any thoughts for implementing a docker environment variable for this?
Oh, and what about using memory to store the playlist and .ts in the docker command for docker to keep file system activity to a minimum? Probably better for pi? Not sure on the best permissions, can probably be 0770.... I set it to 64MB max just to be safe, I know usage is much lower, even with multiple cameras. That is, if I understand tmpfs in docker properly....
`--mount type=tmpfs,destination=/tmp/stream,tmpfs-mode=1770,tmpfs-size=64000000` 
Cheers!

**Comment by gihad** [comment]
Thanks for the review @sreknob! This was really a quick couple of hours project. Did expect anyone else to want to use it.

I fixed the bug you stopped on line 28.

For the improvements you suggested they would all be welcomed. Feel free to make a PR.
