### ISSUE TITLE
Repo Error perhaps, do you know how to fix it?

### ISSUE THREAD

**Issue by Doubleho7** [gihad/streamer#4]
Nice Dock, thanks worked previously but I'm now getting these errors when trying it on my new VM.

$ docker build . -t gihad/streamer
Sending build context to Docker daemon  86.53kB
Step 1/8 : FROM alpine:3.7
3.7: Pulling from library/alpine
911c6d0c7995: Pull complete
Digest: sha256:56e2f91ef15847a2b02a5a03cbfa483949d67a242c37e33ea178e3e7e01e0dfd
Status: Downloaded newer image for alpine:3.7
 ---> 791c3e2ebfcb
Step 2/8 : RUN apk add --update nginx ffmpeg && rm -rf /var/cache/apk/* && mkdir /tmp/stream
 ---> Running in 948a8bc8ab4f
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  ffmpeg (missing):
    required by: world[ffmpeg]
  nginx (missing):
    required by: world[nginx]
The command '/bin/sh -c apk add --update nginx ffmpeg && rm -rf /var/cache/apk/* && mkdir /tmp/stream' returned a non-zero code: 2

**Comment by gihad** [comment]
Looks like a temporary network failure
