### ISSUE TITLE
One stream works fine on chromecast, any more and it gets stuck loading

### ISSUE THREAD

**Issue by smashah** [gihad/streamer#5]
I have 6 cameras running. The m3u8 output from each of them work fine on VLC from another computer on the network.

When I use one stream on the docker image then it streams to chromecast just fine. If I add two or more, the stream is ok for 3 seconds then konks out.

**Comment by skalavala** [comment]
Not sure what hardware you are running, I run 4 streams, and works fine on my server! The CPU and the RAM utilization is also pretty reasonable and low. I have not looked at the disk I/O.

**Comment by gihad** [comment]
If you can set the cameras to output media with codecs AAC and h264 than the program will not need to transcode and it will be very efficient. Otherwise the limit is a matter of resources on your server.
