### ISSUE TITLE
please help newbie

### ISSUE THREAD

**Issue by pmac2785** [gihad/streamer#6]
Hi mate,

I am trying to get streaming to work to my Lenovo smart display.  I have the cameras working on my Hassio instance through ffmpeg using the rtsp stream.

I have a second rpi1 purely running the mqtt server so I thought I would use that pi to run this streaming service.

I ran through the installation process you have and this is the response I get.  Can you please advise what I am doing wrong?

![streamer](https://user-images.githubusercontent.com/31271931/47977450-274cc580-e10c-11e8-8f1e-468f241a7dc1.png)

Thanks for your help.

Cheers,
Patrick

**Comment by bramstroker** [comment]
I have the same error. Don't know how to resolve yet.

**Comment by skalavala** [comment]
Just make sure your username or the passwords do not contain special characters. In my case, I have `!` in my password, and I ran into error. I had to change the password of the cameras. Not sure what other special characters will cause errors, but you get the idea.

**Comment by triorbonk** [comment]
I rebuilt the image 'docker build . -t gihad/streamer' and it worked. 

Download all files in the project to a directory.  
run docker build . -t gihad/streamer within this new directory.
