### ISSUE TITLE
Is it possible to process the input only, when the output is accessed?

### ISSUE THREAD

**Issue by amenk** [gihad/streamer#9]
is it possible to start ffmpeg only when the stream is accessed? i.e. on demand?

**Comment by gihad** [comment]
Yeah, I can think of some ways to do that. Perhaps a simple one would be to use lua and run a script that has a timeout of a few minutes.

You would put the modification inside the location block here: https://github.com/gihad/streamer/blob/master/nginx/nginx.conf#L22

What you could use is `content_by_lua_block`  see https://github.com/openresty/lua-nginx-module#readme
